### ISSUE TITLE
某些候選人資訊頁返回不正確

### ISSUE THREAD

**Issue by lb01910483** [g0v/2020voting-guide#167]
Reproduce

1. click https://vote.ly.g0v.tw/candidate/%E8%8B%97%E6%A0%97%E7%B8%A3%E7%AC%AC%E4%BA%8C%E9%81%B8%E8%88%89%E5%8D%80/%E6%9E%97%E6%98%B1%E5%90%8C

2. 點選左上角返回

3. 返回到 https://vote.ly.g0v.tw/regional

Expect: 

返回至 https://vote.ly.g0v.tw/regional/苗栗縣/苗栗縣第二選舉區

而不是 https://vote.ly.g0v.tw/regional

推論原因:

立委個人資訊缺少資料
"county":"","constituency":""
所以導頁 & 顯示有問題 ( 應該顯示第幾選區 )

**Comment by bangyuwen** [comment]
解決了～看來是抓到舊DB
