### ISSUE TITLE
Design Guideline（部分）

### ISSUE THREAD

**Issue by bangyuwen** [g0v/2020voting-guide#81]
- [x] 界定手機寬度pixel
- [x] 字體

**Comment by chloe-uxdesign** [comment]
確認一下，中文字體應該沒什麼選擇吧？
據我所知都是用系統字  iOS-蘋方 Android-Noto Windows-微軟正黑？

**Comment by bangyuwen** [comment]
還有一個是Google的'Noto Sans TC'/'Noto Serif TC' （思源字體系列）
https://fonts.google.com/specimen/Noto+Sans+TC

**Comment by chloe-uxdesign** [comment]
如果可以用思源的話就用思源是最好!

**Comment by bangyuwen** [comment]
目前用起來蠻正常的，先用用看好了 哈哈
